data:
  image_size: 224
  batch_size: 16
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

model:
  architecture: "efficientnet_b0"
  pretrained: true
  num_classes: 4
  dropout_rate: 0.3

training:
  learning_rate: 0.001
  epochs: 50
  early_stopping_patience: 5

class_names:
  - "adenocarcinoma"
  - "large.cell.carcinoma"
  - "squamous.cell.carcinoma"
  - "normal"