data:
  image_size: 224
  batch_size: 32
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

model:
  architecture: "efficientnet_b0"
  pretrained: true
  num_classes: 2
  dropout_rate: 0.3

training:
  epochs: 50
  learning_rate: 0.001
  early_stopping_patience: 5
  scheduler_patience: 2
  scheduler_factor: 0.1

paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  model_dir: "models"
  
aws:
  model_bucket: "chest-cancer-models"
  data_bucket: "chest-cancer-data"