name: Train and Deploy Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest tests/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Pull data from DVC
      run: |
        dvc pull -r s3remote
        
    - name: Run DVC pipeline
      run: |
        dvc repro
        
    - name: Push metrics to DVC
      run: |
        dvc push -r s3remote

    - name: Deploy model to AWS
      if: github.ref == 'refs/heads/main'
      run: |
        aws s3 cp models/model.pth s3://${{ secrets.AWS_MODEL_BUCKET }}/models/